name: sp-kyc-checks
description: Perform KYC checks against form submissions for Filecoin Storage Providers
runs:
  using: docker
  image: Dockerfile
  entrypoint: /bin/sh
  args:
    - "-c"
    - "mkdir -p output; (cd /usr/src/app && ./sp-kyc-checks testdata/responses-1-pass.json) | tee output/test-results.json"
